version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/DevOps_Test
hooks:
  ApplicationStop:
   - location: ./stop_server.sh
     timeout: 300
     runas: root
  ApplicationStart:
   - location: ./start_server.sh
     timeout: 300
     runas: root